fundamentals = {
    'income-statement': ['NetIncomeExtraordinary', 'ReconciledCostOfRevenue', 'AmortizationOfIntangiblesIncomeStatement', 'TotalRevenue', 
                      'DilutedEPSOtherGainsLosses', 'OtherGandA', 'OtherunderPreferredStockDividend', 'NetIncome', 'GainOnSaleOfBusiness', 
                      'TaxProvision', 'ImpairmentOfCapitalAssets', 'NormalizedEBITDA', 'NetInterestIncome', 'ResearchAndDevelopment', 'WriteOff', 
                      'OperatingRevenue', 'DilutedNIAvailtoComStockholders', 'DilutedEPS', 'TaxLossCarryforwardDilutedEPS', 
                      'SellingGeneralAndAdministration', 'DilutedAverageShares', 'NetIncomeIncludingNoncontrollingInterests', 
                      'NetIncomeContinuousOperations', 'SellingAndMarketingExpense', 'ExciseTaxes', 'OperatingExpense', 'GainOnSaleOfSecurity', 
                      'NetIncomeFromContinuingOperationNetMinorityInterest', 'TaxEffectOfUnusualItems', 'SpecialIncomeCharges', 'SalariesAndWages', 
                      'EarningsFromEquityInterestNetOfTax', 'InterestIncomeNonOperating', 'EBITDA', 'NetIncomeCommonStockholders', 
                      'DilutedExtraordinary', 'OtherNonOperatingIncomeExpenses', 'GrossProfit', 'NormalizedBasicEPS', 
                      'ContinuingAndDiscontinuedBasicEPS', 'ProvisionForDoubtfulAccounts', 'DilutedContinuousOperations', 
                      'BasicEPSOtherGainsLosses', 'BasicContinuousOperations', 'BasicDiscontinuousOperations', 'GeneralAndAdministrativeExpense', 
                      'GainOnSaleOfPPE', 'OtherTaxes', 'NormalizedDilutedEPS', 'OtherOperatingExpenses', 'Amortization', 'ReconciledDepreciation', 
                      'AverageDilutionEarnings', 'EarningsFromEquityInterest', 'NetIncomeFromContinuingAndDiscontinuedOperation', 'EBIT', 
                      'DilutedDiscontinuousOperations', 'NetNonOperatingInterestIncomeExpense', 'DepreciationAmortizationDepletionIncomeStatement', 
                      'SecuritiesAmortization', 'DividendPerShare', 'PreferredStockDividends', 'InterestExpenseNonOperating', 'TotalExpenses', 
                      'ReportedNormalizedDilutedEPS', 'ReportedNormalizedBasicEPS', 'TotalUnusualItemsExcludingGoodwill', 
                      'NetIncomeDiscontinuousOperations', 'DilutedAccountingChange', 'OperatingIncome', 'CostOfRevenue', 'MinorityInterests', 
                      'OtherIncomeExpense', 'NetIncomeFromTaxLossCarryforward', 'InterestIncome', 'BasicExtraordinary', 
                      'TotalOperatingIncomeAsReported', 'RentAndLandingFees', 'RestructuringAndMergernAcquisition', 'TaxLossCarryforwardBasicEPS', 
                      'NormalizedIncome', 'DepreciationAndAmortizationInIncomeStatement', 'DepletionIncomeStatement', 'InsuranceAndClaims', 
                      'TaxRateForCalcs', 'BasicAverageShares', 'ContinuingAndDiscontinuedDilutedEPS', 'InterestExpense', 'BasicEPS', 
                      'BasicAccountingChange', 'DepreciationIncomeStatement', 'TotalOtherFinanceCost', 'RentExpenseSupplemental', 'PretaxIncome', 
                      'TotalUnusualItems', 'OtherSpecialCharges'],
    'balance-sheet': ['CashFinancial', 'CommonStockEquity', 'PensionandOtherPostRetirementBenefitPlansCurrent', 'OtherProperties', 
                         'RestrictedCommonStock', 'InvestmentsAndAdvances', 'CurrentProvisions', 'DuefromRelatedPartiesNonCurrent', 
                         'TotalCapitalization', 'CurrentDeferredTaxesAssets', 'MachineryFurnitureEquipment', 'Properties', 
                         'AssetsHeldForSaleCurrent', 'GoodwillAndOtherIntangibleAssets', 'Goodwill', 'GrossAccountsReceivable', 
                         'OtherEquityInterest', 'InvestmentsinSubsidiariesatCost', 'DerivativeProductLiabilities', 'RetainedEarnings', 
                         'CurrentDeferredTaxesLiabilities', 'DefinedPensionBenefit', 'Leases', 'TradeandOtherPayablesNonCurrent', 
                         'CapitalLeaseObligations', 'AccumulatedDepreciation', 'CurrentDeferredLiabilities', 'NonCurrentDeferredTaxesLiabilities', 
                         'DuetoRelatedPartiesNonCurrent', 'DividendsPayable', 'CurrentDebt', 'TangibleBookValue', 'CurrentLiabilities', 
                         'InvestmentsInOtherVenturesUnderEquityMethod', 'InterestPayable', 'InvestmentProperties', 'OtherIntangibleAssets', 
                         'LoansReceivable', 'FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal', 'PayablesAndAccruedExpenses', 
                         'PreferredStock', 'CurrentCapitalLeaseObligation', 'TaxesReceivable', 'StockholdersEquity', 'ShareIssued', 
                         'HedgingAssetsCurrent', 'NonCurrentDeferredAssets', 'WorkingCapital', 'PreferredStockEquity', 
                         'TotalNonCurrentLiabilitiesNetMinorityInterest', 'NonCurrentPrepaidAssets', 'AccountsReceivable', 
                         'InventoriesAdjustmentsAllowances', 'NotesReceivable', 'LimitedPartnershipCapital', 'OtherEquityAdjustments', 
                         'OtherNonCurrentAssets', 'NonCurrentDeferredTaxesAssets', 'EmployeeBenefits', 'OtherCurrentLiabilities', 'OtherPayable', 
                         'CashEquivalents', 'LongTermEquityInvestment', 'MinimumPensionLiabilities', 'CurrentNotesPayable', 'Inventory', 
                         'TotalPartnershipCapital', 'InvestedCapital', 'OtherCurrentBorrowings', 'TreasurySharesNumber', 'NetTangibleAssets', 
                         'InvestmentinFinancialAssets', 'Payables', 'LongTermCapitalLeaseObligation', 'LandAndImprovements', 'PrepaidAssets', 
                         'ForeignCurrencyTranslationAdjustments', 'AdditionalPaidInCapital', 'OtherInvestments', 'GrossPPE', 
                         'BuildingsAndImprovements', 'CashCashEquivalentsAndShortTermInvestments', 'CurrentAssets', 'TreasuryStock', 
                         'OtherShortTermInvestments', 'LineOfCredit', 'CashAndCashEquivalents', 'LongTermDebtAndCapitalLeaseObligation',
                         'CapitalStock', 'RestrictedCash', 'FinancialAssets', 'AvailableForSaleSecurities', 'FixedAssetsRevaluationReserve', 
                         'ConstructionInProgress', 'OtherCurrentAssets', 'HeldToMaturitySecurities', 'CurrentAccruedExpenses', 
                         'AllowanceForDoubtfulAccountsReceivable', 'NonCurrentAccountsReceivable', 'CommercialPaper', 
                         'InvestmentsinAssociatesatCost', 'AccruedInterestReceivable', 'NonCurrentAccruedExpenses', 'TotalAssets', 'CommonStock', 
                         'LongTermDebt', 'NonCurrentPensionAndOtherPostretirementBenefitPlans', 'CurrentDebtAndCapitalLeaseObligation', 
                         'NonCurrentNoteReceivables', 'AccountsPayable', 'TotalLiabilitiesNetMinorityInterest', 'InvestmentsinJointVenturesatCost', 
                         'OtherInventories', 'UnrealizedGainLoss', 'GainsLossesNotAffectingRetainedEarnings', 'TotalNonCurrentAssets', 
                         'OtherReceivables', 'PreferredSharesNumber', 'TotalTaxPayable', 'IncomeTaxPayable', 'CurrentDeferredAssets', 
                         'TotalEquityGrossMinorityInterest', 'RawMaterials', 'DuefromRelatedPartiesCurrent', 'NonCurrentDeferredRevenue', 
                         'TotalDebt', 'OtherCapitalStock', 'NetDebt', 'PreferredSecuritiesOutsideStockEquity', 'NonCurrentDeferredLiabilities', 
                         'WorkInProcess', 'DuetoRelatedPartiesCurrent', 'LiabilitiesHeldforSaleNonCurrent', 'OrdinarySharesNumber', 
                         'TradingSecurities', 'ReceivablesAdjustmentsAllowances', 'Receivables', 'OtherNonCurrentLiabilities', 
                         'GeneralPartnershipCapital', 'NetPPE', 'LongTermProvisions', 'FinishedGoods', 
                         'CurrentDeferredRevenue', 'MinorityInterest'],
    'cash-flow': ['PensionAndEmployeeBenefitExpense', 'ChangesInCash', 'NetPPEPurchaseAndSale', 'ChangeInAccruedExpense', 'ChangeInPayable', 
                  'DomesticSales', 'ChangeInOtherCurrentLiabilities', 'PaymentsonBehalfofEmployees', 'NetInvestmentPropertiesPurchaseAndSale', 
                  'DividendReceivedCFO', 'PurchaseOfInvestmentProperties', 'OtherCashAdjustmentOutsideChangeinCash', 
                  'ExcessTaxBenefitFromStockBasedCompensation', 'ProceedsFromStockOptionExercised', 'OtherCashAdjustmentInsideChangeinCash', 
                  'NetIssuancePaymentsOfDebt', 'PurchaseOfPPE', 'CapitalExpenditure', 'CommonStockDividendPaid', 'DeferredIncomeTax', 
                  'GainLossOnSaleOfPPE', 'CommonStockPayments', 'DividendsReceivedDirect', 'EarningsLossesFromEquityInvestments', 
                  'NetInvestmentPurchaseAndSale', 'PreferredStockDividendPaid', 'InterestReceivedCFO', 'FinancingCashFlow', 'ChangeInWorkingCapital', 
                  'PaymentstoSuppliersforGoodsandServices', 'UnrealizedGainLossOnInvestmentSecurities', 'NetCommonStockIssuance', 
                  'OtherCashPaymentsfromOperatingActivities', 'CashFlowFromDiscontinuedOperation', 'ChangeInOtherCurrentAssets', 
                  'InterestPaidSupplementalData', 'BeginningCashPosition', 'NetOtherFinancingCharges', 'Depletion', 'NetPreferredStockIssuance', 
                  'ProvisionandWriteOffofAssets', 'DividendPaidCFO', 'PurchaseOfIntangibles', 'CashFlowsfromusedinOperatingActivitiesDirect', 
                  'DepreciationAmortizationDepletion', 'TaxesRefundPaid', 'InterestReceivedCFI', 'NetIntangiblesPurchaseAndSale', 
                  'CashFromDiscontinuedOperatingActivities', 'LongTermDebtPayments', 'NetBusinessPurchaseAndSale', 'NetOtherInvestingChanges', 
                  'InterestPaidCFO', 'ReceiptsfromCustomers', 'ShortTermDebtPayments', 'CashDividendsPaid', 'ChangeInInventory', 
                  'LongTermDebtIssuance', 'PreferredStockIssuance', 'AmortizationOfIntangibles', 'SaleOfIntangibles', 'TaxesRefundPaidDirect', 
                  'GainLossOnSaleOfBusiness', 'PreferredStockPayments', 'AmortizationOfSecurities', 'SaleOfPPE', 
                  'CashFromDiscontinuedFinancingActivities', 'CashFromDiscontinuedInvestingActivities', 'PurchaseOfInvestment', 
                  'EffectOfExchangeRateChanges', 'ChangeInAccountPayable', 'ChangeInOtherWorkingCapital', 'DepreciationAndAmortization',
                  'SaleOfInvestmentProperties', 'OperatingCashFlow', 'CashFlowFromContinuingInvestingActivities', 'DeferredTax', 
                  'ChangesInAccountReceivables', 'EndCashPosition', 'RepurchaseOfCapitalStock', 'InvestingCashFlow', 'ChangeInDividendPayable', 
                  'ChangeInTaxPayable', 'OtherNonCashItems', 'OperatingGainsLosses', 'CapitalExpenditureReported', 
                  'NetForeignCurrencyExchangeGainLoss', 'NetIncomeFromContinuingOperations', 'GainLossOnInvestmentSecurities', 
                  'CashFlowFromContinuingOperatingActivities', 'ChangeInPayablesAndAccruedExpense', 'IncomeTaxPaidSupplementalData', 
                  'RepaymentOfDebt', 'OtherCashReceiptsfromOperatingActivities', 'ReceiptsfromGovernmentGrants', 'IssuanceOfCapitalStock', 
                  'NetLongTermDebtIssuance', 'AmortizationCashFlow', 'CashFlowFromContinuingFinancingActivities', 'ChangeInPrepaidAssets', 
                  'ChangeInReceivables', 'AssetImpairmentCharge', 'DividendsPaidDirect', 'PurchaseOfBusiness', 'StockBasedCompensation', 
                  'Depreciation', 'IssuanceOfDebt', 'ChangeInInterestPayable', 'AdjustedGeographySegmentData', 'NetShortTermDebtIssuance', 
                  'ClassesofCashPayments', 'ForeignSales', 'SaleOfInvestment', 'ShortTermDebtIssuance', 'InterestPaidDirect', 'FreeCashFlow', 
                  'InterestReceivedDirect', 'ClassesofCashReceiptsfromOperatingActivities', 'SaleOfBusiness', 'DividendsReceivedCFI', 
                  'CommonStockIssuance', 'InterestPaidCFF', 'ChangeInIncomeTaxPayable']
}
statistics = {
    'information': []
}